//Created by: Madhan KAMALAKANNAN,  Nov/2022s
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace onlinesupermartSQLElasticDB.Models
{
    public partial class ActivationCode
    {
        public int Id { get; set; }
        public int? ProductsId { get; set; }
        public int? OrderDetailsId { get; set; }
    }
}