//Created by: Madhan KAMALAKANNAN,  Aug/2022
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace onlinesupermartSQLElasticDB.Models
{
    public partial class CartDetails
    {
        public int Id { get; set; }
        public int? CartId { get; set; }
        public int? ProductsId { get; set; }
        public int? ShippingOptionId { get; set; }
        public int? CouponId { get; set; }
        public decimal? TotalPrice { get; set; }
        public int? Qty { get; set; }

        public virtual Cart Cart { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual Products Products { get; set; }
        public virtual ShippingOptions ShippingOption { get; set; }
    }
}