//Created by: Madhan KAMALAKANNAN,  Aug/2022
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace onlinesupermartSQLElasticDB.Models
{
    public class PaymentTypes
    {
        public PaymentTypes()
        {
            Payment = new HashSet<Payment>();
        }

        public int Id { get; set; }
        public string PaymentType { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
     
    }
}