//Created by: Madhan KAMALAKANNAN,  Aug/2022
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace onlinesupermartSQLElasticDB.Models
{
    public partial class Payment
    {
        public int Id { get; set; }
        public int? PaymentTypeId { get; set; }
        public int? OrderId { get; set; }
        public int? CartId { get; set; }
        public decimal? Payment1 { get; set; }
        public string Status { get; set; }
        public DateTime? DateTime { get; set; }

        public virtual Cart Cart { get; set; }
        public virtual Orders Order { get; set; }
        public virtual PaymentTypes PaymentType { get; set; }
    }
}