//Created by: Madhan KAMALAKANNAN,  Aug/2022
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace onlinesupermartSQLElasticDB.Models
{
    public partial class PaymentsTypes
    {
        public PaymentsTypes()
        {
            Payments = new HashSet<Payments>();
        }

        public int Id { get; set; }
        public string PaymentType { get; set; }

        public virtual ICollection<Payments> Payments { get; set; }
    }
}