//Created by: Madhan KAMALAKANNAN,  Aug/2022
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace onlinesupermartSQLElasticDB.Models
{
    public partial class ProductsTemp
    {
        public ProductsTemp()
        {
           
        }

        public string Id { get; set; }   
        public string Quantity { get; set; }
       
    }
}