//Created by: Madhan KAMALAKANNAN,  Aug/2022
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace onlinesupermartSQLElasticDB.Models
{
    public partial class Products
    {
        public Products()
        {
            CartDetails = new HashSet<CartDetails>();
            OrdersDetails = new HashSet<OrdersDetails>();
            ProductsReview = new HashSet<ProductsReview>();
        }

        public int Id { get; set; }
        public int? ProductsCategoriesId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal? Price { get; set; }
        public string ProductsPic { get; set; }
        public string ActivationCodes { get; set; }
        public string ShowtoSale { get; set; }
        public int? Quantity { get; set; }

        public virtual ProductsCategories ProductsCategories { get; set; }
        public virtual ICollection<CartDetails> CartDetails { get; set; }
        public virtual ICollection<OrdersDetails> OrdersDetails { get; set; }
        public virtual ICollection<ProductsReview> ProductsReview { get; set; }
    }
}