//Created by: Madhan KAMALAKANNAN,  Aug/2022
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace onlinesupermartSQLElasticDB.Models
{
    public partial class ProductsReview
    {
        public int Id { get; set; }
        public int? ProductsId { get; set; }
        public string Review { get; set; }
        public Guid? UserId { get; set; }
        public string Rating { get; set; }
        public string UserName { get; set; }

        public virtual Products Products { get; set; }
        public virtual AspNetUsers User { get; set; }
    }
}