//Created by: Madhan KAMALAKANNAN,  Aug/2022
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace onlinesupermartSQLElasticDB.Models
{
    public partial class ProductsCategories
    {
        public ProductsCategories()
        {
            Products = new HashSet<Products>();
        }

        public int Id { get; set; }
        public int? ParentId { get; set; }
        public string CategoryDesc { get; set; }
        public string CategoryName { get; set; }
        public string NavUrl { get; set; }

        public virtual ICollection<Products> Products { get; set; }
    }
}