//Created by: Madhan KAMALAKANNAN,  Aug/2022
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace onlinesupermartSQLElasticDB.Models
{
    public partial class ShippingOptions
    {
        public ShippingOptions()
        {
            CartDetails = new HashSet<CartDetails>();
        }

        public int Id { get; set; }
        public string ShippingOptionDesc { get; set; }
        public string ShippingOption { get; set; }
        public decimal? ShippingCost { get; set; }
        public string ShippingDestinationCountry { get; set; }
        public string ShippingDestinationState { get; set; }
        public string ShippingDetinationOtherDetails { get; set; }

        public virtual ICollection<CartDetails> CartDetails { get; set; }
    }
}